# Aufruf:   cp ...
#           docker compose -f compose.busybox.yml up
#           docker compose exec busybox ash
#               busybox
#               nslookup postgres
#               nslookup keycloak
#               exit
#           docker compose -f compose.busybox.yml down

services:
  busybox:
    image: busybox:1.37.0
    command:
      [
        "sh",
        "-c",
        "echo 'Container mit busybox ist gestartet.' && sleep infinity",
      ]
    networks: [acme-network]
    hostname: busybox
    cap_drop: [ALL]
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 768M

networks:
  acme-network:
    name: acme-network
