name: Lint and Format

on:
  push:
    branches:
      - '**'

jobs:
  lint-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: |
          echo "Running ESLint (ignores exit code)..."
          npm run eslint || true

      - name: Run Prettier Check
        run: |
          echo "Running Prettier check (ignores exit code)..."
          npm run prettier:check || true
